### ISSUE TITLE
Class 'BackupExport' not found

### ISSUE THREAD

**Issue by John-Henrique** [mirko-pagliai/cakephp-database-backup#30]
CakePHP: **3.6.5**
PHP: **7.1**
Database: **Sqlite**
DatabaseBackup: **2.5.0**

**Scenario**
Added 

` use DatabaseBackup\Utility\BackupExport; // plugin BackupExport` 

in PagesController, added 

`Plugin::load('DatabaseBackup', ['bootstrap' => true]); `

in App/bootstrap.php

In home.ctp added 
``` 
            $backup = new BackupExport();
            $backup->compression('gzip');
            $backup->rotate();
            $filename = $backup->export(); 
``` 

When run localhost/app (my app), I get error 
> Class 'BackupExport' not found

> Error in: ROOT\src\Template\Pages\home.ctp, line 128
If you want to customize this error message, create src\Template\Error\error500.ctp

> Cake\Controller\Controller->render APP/Controller\PagesController.php, line 63

**Question**
What I doing wrong?

**Comment by mirko-pagliai** [comment]
You declared the namespace in the controller, while you instantiated the class in the view.

However, I do not recommend using the plugin in the view, it is improper practice. You should move all the code in the controller.
