### ISSUE TITLE
Cannot export my data

### ISSUE THREAD

**Issue by Awesomniac** [mirko-pagliai/cakephp-database-backup#41]
Hello guys i am a newbie :p 
I loaded the plugin and configured what is necessary but when i want to export the data i get this error :
"Expected configuration key "DatabaseBackup.binaries.mysqldump" not found."
In my controller i added a function :
   public function backup(){
        $backup = new BackupExport();
        $backup->compression('gzip');
        $backup->export();
    }
can you please help me.

**Comment by mirko-pagliai** [comment]
This does not seem like a bug.

Can you post a full log? Plugin version?  Version of Cakephp? `mysqldump` is installed? This could be the problem

**Comment by Awesomniac** [comment]
Mysqldump is apparently installed ,i am using the wamp server ,my versions are :
MySQL 5.7.23
cakephp v3.7.7

**Comment by mirko-pagliai** [comment]
"Wamp" is Windows, I think.

It just seems like the plugin can't find the `mysqldump` binary, although you should post at least a log to make sure this is the problem.

Try to set the full path for `mysqldump` *before* to load the plugin:
https://github.com/mirko-pagliai/cakephp-database-backup/wiki/Configuration#binaries

Something like this:

    Configure::write('DatabaseBackup.bin.bzip2', 'C:\\full\\path\\to\\mysqldump');

**Comment by Awesomniac** [comment]
I am sorry for bothering you :p
i did what you said 
 Configure::write('DatabaseBackup.bin.mysqldump', 'C:\wamp64\bin\mysql\mysql5.7.23\bin\mysqldump');
 $this->addPlugin('DatabaseBackup',['bootstrap' => true]);
but still the same error there is the full log
[RuntimeException] Expected configuration key "DatabaseBackup.binaries.mysqldump" not found. #0 C:\CakeJui\cake4\vendor\mirko-pagliai\cakephp-database-backup\src\BackupTrait.php(53): Cake\Core\Configure::readOrFail('DatabaseBackup....') #1 C:\CakeJui\cake4\vendor\mirko-pagliai\cakephp-database-backup\src\Driver\Mysql.php(40): DatabaseBackup\Driver\Driver->getBinary('mysqldump') #2 C:\CakeJui\cake4\vendor\mirko-pagliai\cakephp-database-backup\src\Driver\Driver.php(125): DatabaseBackup\Driver\Mysql->_exportExecutable() #3 C:\CakeJui\cake4\vendor\mirko-pagliai\cakephp-database-backup\src\Driver\Driver.php(185): DatabaseBackup\Driver\Driver->_exportExecutableWithCompression('C:\\CakeJui\\cake...') #4 C:\CakeJui\cake4\vendor\mirko-pagliai\cakephp-database-backup\src\Utility\BackupExport.php(226): DatabaseBackup\Driver\Driver->export('C:\\CakeJui\\cake...') #5 C:\CakeJui\cake4\src\Controller\RaysController.php(25): DatabaseBackup\Utility\BackupExport->export() #6 C:\CakeJui\cake4\vendor\cakephp\cakephp\src\Controller\Controller.php(610): App\Controller\RaysController->backup() #7 C:\CakeJui\cake4\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(120): Cake\Controller\Controller->invokeAction() #8 C:\CakeJui\cake4\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(94): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\RaysController)) #9 C:\CakeJui\cake4\vendor\cakephp\cakephp\src\Http\BaseApplication.php(235): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response)) #10 C:\CakeJui\cake4\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner)) #11 C:\CakeJui\cake4\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner)) #12 C:\CakeJui\cake4\vendor\cakephp\cakephp\src\Http\Middleware\CsrfProtectionMiddleware.php(108): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response)) #13 C:\CakeJui\cake4\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\Middleware\CsrfProtectionMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner)) #14 C:\CakeJui\cake4\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response)) #15 C:\CakeJui\cake4\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(168): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response)) #16 C:\CakeJui\cake4\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner)) #17 C:\CakeJui\cake4\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response)) #18 C:\CakeJui\cake4\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner)) #19 C:\CakeJui\cake4\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(96): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response)) #20 C:\CakeJui\cake4\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner)) #21 C:\CakeJui\cake4\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(53): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response)) #22 C:\CakeJui\cake4\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner)) #23 C:\CakeJui\cake4\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response)) #24 C:\CakeJui\cake4\vendor\cakephp\cakephp\src\Http\Server.php(98): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response)) #25 C:\CakeJui\cake4\webroot\index.php(40): Cake\Http\Server->run() #26 {main} Request URL: /rays/backup

**Comment by mirko-pagliai** [comment]
Please: 
1) delete the log files 
2) run the action again
3) open, copy and paste the contents of the log using the formatting, otherwise it will be illegible

**Comment by mirko-pagliai** [comment]
Were you able to solve or do you still have the same problem?

**Comment by mirko-pagliai** [comment]
Please, try the new release `2.6.4`:
https://github.com/mirko-pagliai/cakephp-database-backup/releases/tag/2.6.4

**Comment by Awesomniac** [comment]
I apologize for the delayed response, I managed to solve my problem,  I used your plugin and I thank you for your help
