### ISSUE TITLE
Binary for mysqldump could not be found.

### ISSUE THREAD

**Issue by deb986** [mirko-pagliai/cakephp-database-backup#57]
Hello guys i am a newbie .

Using cakephp4 in windows xampp , I loaded this plugin and configured what is necessary but when i want to export the DB i get this error  : 

code "
$backup = new BackupExport();
$backup->compression('gzip');
$filename = $backup->export();
"

Error log : 

2020-04-28 04:37:59 Error: [RuntimeException] Binary for `mysqldump` could not be found. You have to set its path manually in C:\xampp\htdocs\my_cakephp4\vendor\mirko-pagliai\php-tools\src\or_fail_functions.php on line 162
Stack Trace:
- C:\xampp\htdocs\my_cakephp4\vendor\mirko-pagliai\cakephp-database-backup\src\Driver\Driver.php:205
- C:\xampp\htdocs\my_cakephp4\vendor\mirko-pagliai\cakephp-database-backup\src\Driver\Mysql.php:42
- C:\xampp\htdocs\my_cakephp4\vendor\mirko-pagliai\cakephp-database-backup\src\Driver\Driver.php:129
- C:\xampp\htdocs\my_cakephp4\vendor\mirko-pagliai\cakephp-database-backup\src\Driver\Driver.php:188
- C:\xampp\htdocs\my_cakephp4\vendor\mirko-pagliai\cakephp-database-backup\src\Utility\BackupExport.php:225
- C:\xampp\htdocs\my_cakephp4\src\Controller\PagesController.php:52
- C:\xampp\htdocs\my_cakephp4\vendor\cakephp\cakephp\src\Controller\Controller.php:521
- C:\xampp\htdocs\my_cakephp4\vendor\cakephp\cakephp\src\Controller\ControllerFactory.php:79
- C:\xampp\htdocs\my_cakephp4\vendor\cakephp\cakephp\src\Http\BaseApplication.php:229
- C:\xampp\htdocs\my_cakephp4\vendor\cakephp\cakephp\src\Http\Runner.php:77
- C:\xampp\htdocs\my_cakephp4\vendor\cakephp\cakephp\src\Http\Runner.php:77
- C:\xampp\htdocs\my_cakephp4\vendor\cakephp\cakephp\src\Http\Middleware\CsrfProtectionMiddleware.php:137
- C:\xampp\htdocs\my_cakephp4\vendor\cakephp\cakephp\src\Http\Runner.php:73
- C:\xampp\htdocs\my_cakephp4\vendor\cakephp\cakephp\src\Http\Runner.php:58
- C:\xampp\htdocs\my_cakephp4\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php:162
- C:\xampp\htdocs\my_cakephp4\vendor\cakephp\cakephp\src\Http\Runner.php:73
- C:\xampp\htdocs\my_cakephp4\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php:68
- C:\xampp\htdocs\my_cakephp4\vendor\cakephp\cakephp\src\Http\Runner.php:73
- C:\xampp\htdocs\my_cakephp4\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php:119
- C:\xampp\htdocs\my_cakephp4\vendor\cakephp\cakephp\src\Http\Runner.php:73
- C:\xampp\htdocs\my_cakephp4\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php:60
- C:\xampp\htdocs\my_cakephp4\vendor\cakephp\cakephp\src\Http\Runner.php:73
- C:\xampp\htdocs\my_cakephp4\vendor\cakephp\cakephp\src\Http\Runner.php:58
- C:\xampp\htdocs\my_cakephp4\vendor\cakephp\cakephp\src\Http\Server.php:90
- C:\xampp\htdocs\my_cakephp4\webroot\index.php:40

Request URL: /

Please guide me how to fix this

**Comment by mirko-pagliai** [comment]
Hi @deb986,

the error message seems clear fot me. Did you follow the wiki instructions? Is the `mysqldump` binary present

**Comment by deb986** [comment]
Configure::write('DatabaseBackup.bin.mysql', ROOT . DS . 'C:\xampp\mysql\bin');

yes added above line.
If i'm wrong please, correct me.

**Comment by mirko-pagliai** [comment]
@deb986 `ROOT` and` DS` are constants that point to other paths. See [the wiki](https://github.com/mirko-pagliai/cakephp-database-backup/wiki/Configuration#binaries), please.

If the `mysql` binary is in `C:\xampp\mysql\bin\mysql`, it should be something like this:
```php
Configure::write('DatabaseBackup.bin.mysql', 'C:\xampp\mysql\bin\mysql');
```

But I can't know where it is...

The same thing should probably be done for `mysqldump` and `gzip`.

**Comment by mirko-pagliai** [comment]
@deb986 see https://stackoverflow.com/questions/698914/how-can-i-access-the-mysql-command-line-with-xampp-for-windows

So maybe:
```php
Configure::write('DatabaseBackup.bin.mysql', 'C:\xampp\mysql\bin\mysql.exe');
Configure::write('DatabaseBackup.bin.mysqldump', 'C:\xampp\mysql\bin\mysqldump.exe');
```
You can use the explorer to verify that those files exist at that path. I don't use Windows, nor Xammp, so I wouldn't know any further.

I guess Gzip needs to be installed separately.

**Comment by deb986** [comment]
Gzip already present in xampp.
mysql.exe and mysqldump.exe present in bin folder.

Checked using your suggestion still showing the same error.

Okay thanks.

**Comment by mirko-pagliai** [comment]
This does not seem possible.  Is the configuration written before loading the plugin?

**Comment by deb986** [comment]
yes, in app.php file

**Comment by mirko-pagliai** [comment]
`app.php` is not a good place. The file should only return an array with the app configuration.
It should be in the bootstrap file.

**Comment by deb986** [comment]
Yes, already chekced that and also checked by putting on same controller. Always shows same error.

**Comment by mirko-pagliai** [comment]
This is the code that throws the exception:
https://github.com/mirko-pagliai/cakephp-database-backup/blob/master/src/Driver/Driver.php#L203

This means that
```php
Configure::read('DatabaseBackup.binaries.mysqldump')
```
is `null` or` false`. I'm sorry, but there is no other explanation. Surely you're doing something wrong that we can't understand here.

The bootstrap of the plugin tries to auto-set the binaries, if they have not already been set manually:
https://github.com/mirko-pagliai/cakephp-database-backup/blob/master/config/bootstrap.php
This however does not work on Windows systems.
