### ISSUE TITLE
Deprecated. Use instead `Filesystem::getExtension()`

### ISSUE THREAD

**Issue by mixable** [mirko-pagliai/cakephp-database-backup#60]
When using the plugin with the latest version of [phptools](https://github.com/mirko-pagliai/php-tools) (1.4.4), the following warnings are raised:

get_extension() ... Deprecated. Use instead `Filesystem::getExtension()`
add_slash_term() ... Deprecated. Use instead `Filesystem::addSlashTerm()`

**Comment by mirko-pagliai** [comment]
Hi @mixable, yes, I know, also because that package is always mine. 

For now you can silence the error, an update will come out soon.

**Comment by mirko-pagliai** [comment]
Fixed with the new release
https://github.com/mirko-pagliai/cakephp-database-backup/releases/tag/2.8.3
