### ISSUE TITLE
Parametri per esportazione ( statistiche )

### ISSUE THREAD

**Issue by rudy1976s** [mirko-pagliai/cakephp-database-backup#75]
Hi
I had an issue esporting database due to my version of MySql, which does not allow the following parameter:

`--column-statistics=1
`

To make export working again I had to dig into the mysql driver code and add the parameter to the **_exportExecutable** function

`--column-statistics=0
`
```
return sprintf(
      '%s --defaults-file=%s %s %s',
      escapeshellarg($this->getBinary('mysqldump')),
      escapeshellarg($this->auth),
      escapeshellarg($this->getConfig('database')),
      escapeshellarg('--column-statistics=0')
  );
```

Is there a clean way to pass this further parameter to the function ? 

Thanks 

Rudy

**Comment by mirko-pagliai** [comment]
@rudy1976s which version of mysql are you using?

**Comment by rudy1976s** [comment]
> @rudy1976s which version of mysql are you using?

We have 5.7

**Comment by rudy1976s** [comment]
> Currently the `--column-statistics` option is not used by `DatabaseBackup\Driver\MySql::_exportExecutable()` ([code](https://github.com/mirko-pagliai/cakephp-database-backup/blob/2.9.1/src/Driver/Mysql.php#L37)).
> 
> Although I remember thinking about introducing it. What version of the package are you using?

In fact I have added it manually to make it work.
I am working on the last version

**Comment by mirko-pagliai** [comment]
So it only works by adding the `--column-statistics` option with `0` value?

What happens with the value `1` instead?
I find it a bit difficult to test all the various environments (unix, win, various php versions, various mysql and postgres version). I can however find a way to set extra options in the configuration.

**Comment by rudy1976s** [comment]
> So it only works by adding the `--column-statistics` option with `0` value?
> 
> What happens with the value `1` instead? I find it a bit difficult to test all the various environments (unix, win, various php versions, various mysql and postgres version). I can however find a way to set extra options in the configuration.

Under my actual version of mysql, using 1 it fails because such function is not supported: the best way would be to to have the possibility of adding extra parameters passed as parameters

**Comment by mirko-pagliai** [comment]
PR https://github.com/mirko-pagliai/cakephp-database-backup/pull/77

**Comment by mirko-pagliai** [comment]
Hi @rudy1976s 

try the version [2.10.0-beta1](https://github.com/mirko-pagliai/cakephp-database-backup/releases/tag/2.10.0-beta1) (which for now is beta, because important changes have been made and therefore I will wait a bit of running in before declaring it stable).

Follow the [instructions given in the wiki](https://github.com/mirko-pagliai/cakephp-database-backup/wiki/Configuration#customize-exportimport-commands).

Give me feedback as soon as possible.
