### ISSUE TITLE
Missing dependency pguardiario/phpuri

### ISSUE THREAD

**Issue by UrizenAtW2C** [mirko-pagliai/cakephp-database-backup#85]
I try to install, but i got an error. it`s seems that pguardiario/phpuri dependency is missing

**Comment by mirko-pagliai** [comment]
it depends on an external package that was suddenly deleted. I will fix it
within a few days

Il sab 4 feb 2023, 20:25 UrizenAtW2C ***@***.***> ha scritto:

**Comment by mirko-pagliai** [comment]
Fixed with the new release.
Note that at least PHP 7.4 is required as of now.

Let me know if everything is ok for you.

**Comment by UrizenAtW2C** [comment]
Everithing ok. Thank you for this fix
