### ISSUE TITLE
ProcessTimedOutException: The process "'/usr/bin/mysqldump' ..." exceeded the timeout of 60 seconds.

### ISSUE THREAD

**Issue by mixable** [mirko-pagliai/cakephp-database-backup#88]
When I create the database backup, I receive a ProcessTimedOutException. The backup uses mysqldump and gzip to create a backup file in the file system.

Here is the exception:
```
[Symfony\Component\Process\Exception\ProcessTimedOutException] The process "'/usr/bin/mysqldump' ...  | '/bin/gzip' > ..." exceeded the timeout of 60 seconds. in .../vendor/symfony/process/Process.php on line 1154
```

This is the Stack Trace:
```
/vendor/symfony/process/Process.php:423]
- /vendor/symfony/process/Process.php:249]
- /vendor/mirko-pagliai/cakephp-database-backup/src/Driver/Driver.php:78]
- /vendor/mirko-pagliai/cakephp-database-backup/src/Driver/Driver.php:229]
- /vendor/mirko-pagliai/cakephp-database-backup/src/Utility/BackupExport.php:199]
- /src/Command/AppBackupCommand.php:59]
- /vendor/cakephp/cakephp/src/Console/BaseCommand.php:189]
- /vendor/cakephp/cakephp/src/Console/BaseCommand.php:282]
- /src/Command/CronjobCommand.php:230]
- /src/Command/CronjobCommand.php:119]
- /vendor/cakephp/cakephp/src/Console/BaseCommand.php:189]
- /vendor/cakephp/cakephp/src/Console/CommandRunner.php:334]
- /vendor/cakephp/cakephp/src/Console/CommandRunner.php:172]
- /bin/cake.php:12]
```

When looking at the Driver in `DatabaseBackup\Driver\Driver`, the method `_exec` on line 75 uses `Process::fromShellCommandline()` which is causing the exception:

```php
    protected function _exec(string $command): Process
    {
        $process = Process::fromShellCommandline($command);
        $process->run();

        return $process;
    }
```

The [documentation of Process](https://symfony.com/doc/current/components/process.html#process-timeout) mentions a `setTimeout()` method, which allows the increase of the default value of 60 seconds.

I would suggest to add this method and use a configuration value to specify a larger user value: 

```php
    protected function _exec(string $command): Process
    {
        $process = Process::fromShellCommandline($command);
        $process->setTimeout(Configure::read('DatabaseBackup.processTimeout', 60));
        $process->run();

        return $process;
    }
```

I tested this with a larger value of 300 seconds and the backup was created without exception.

**Comment by mirko-pagliai** [comment]
Hi @mixable and thanks for your feedback, it is really very useful.

Can I ask you what are the size of the database AND what of the finally exported file? Also the size of the exported database WITHOUT compression. I guess that's the problem, but just so I realize.

Thanks again.

**Comment by mixable** [comment]
Hi @mirko-pagliai ,

Here are some numbers: the database has 107 tables and a total size of 105.8 MB.

The execution of `BackupExport` **with compression** enabled:
```php
        $backup = new BackupExport();
        $filename = $backup
            ->compression('gzip')
            ->rotate(10)
            ->export();
```
This results in a gzip file of **130 MB** and the execution time is **79.205482006073 sec**.

And **without compression**:
```php
        $backup = new BackupExport();
        $filename = $backup
            ->rotate(10)
            ->export();
```
This results in a sql file of **1,20 GB** and the execution time is **65.016938209534 sec**.

As you already thought, the compression is a big part of the backup. But even without compression, the execution time is over 60 seconds. This was not a problem in the past, but I thing the increasing size of the database over time now hit this limit.

**Comment by mirko-pagliai** [comment]
[Release 2.12.0](https://github.com/mirko-pagliai/cakephp-database-backup/releases/tag/2.12.0) added `BackupExport::timeout()` and `BackupImport::timeout()` methods and `--timeout` option for `ExportCommand` and `ImportCommand`.
